language: php

php:
  - 5.3.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - rm -rf drush
  - git clone --branch 7.x-5.x git://git.drupal.org/project/drush.git drush
  - chmod +x drush/drush
  - drush/drush make build-commons-dev.make --no-cache -y
  
script:
    - exit